### ISSUE TITLE
DAS Portal

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das-frontend#1]
The portal will be a static page for the system. Navigation in landing page should include:
 - DAS Home
 - Link to Upcoming Competitions
 - Link to Competition Results
 - Link to Leaderboards
 - Link to Profiles
 - Link to DAS Account Registration
 - Link to Account Sign In

**Comment by yubing24** [comment]
We should split the front page into several sections. Here are some ideas.
- Section 1:
  - A slideshow of pictures from competitions (preferably public domain)
  - A headline for Dancesport Application System (DAS) (what we have is good for now)
  - An indication of "in development" status 
- Section 2
  - List of main features (not a finalized list yet)
    - Latest Technology
    - Built for different federations and rules
    - Open to developers
- Section 3 (Similar to the Angular version)
    - Separated lists of features that we are going to have for MVP
    - An indication of the status of listed features (optional)
- Section 4 
    - Want to Help?
      - Github Org
      - List of 3 Repos on Github: das, dasdb, das-frontend
      - Slack Channel
- Footer: 
      - Instead of using "Dancesport Software", let's use "DAS Development Team", and create a separate page "/team", which we can put team member photos (optional) and bios.

**Comment by shadowlion** [comment]
@yubing24 you should make each of them into separate cards

**Comment by yubing24** [comment]
Current implementation suffice the needs for now. Close issue.
![implementation 2018-12-13](https://user-images.githubusercontent.com/10504139/49972731-2c194c00-fef8-11e8-93aa-bfccad569e3e.jpg)
