### ISSUE TITLE
Competition Creation Form

### ISSUE THREAD

**Issue by shadowlion** [DancesportSoftware/das-frontend#13]
A User with a Role of Organizer needs the following information filled out on a form:

- Competition name
- Dance Federation
- Address
- City
- State (/Province)
- (Country)
- Zip/Postal Code
- Start Datetime object
- End Datetime object
- Contact email
- Contact phone

Other JSON payload variables that needed to be packaged into the API call:

- Header: `Content-Type: application-json`

Response:

- **Success!** - 200
- **Failure** - 400, 401, 403, 500

Reference: [POSTman docs](https://documenter.getpostman.com/view/2986351/RWEfMemn#671078cf-aefb-8570-46d2-73aa7cf05207), competition creation

**Comment by shadowlion** [comment]
@yubing24 should this be closed, now that it's been resolved?

**Comment by yubing24** [comment]
Issue is resolved with PR #81
