### ISSUE TITLE
Event Creation (per Competition)

### ISSUE THREAD

**Issue by shadowlion** [DancesportSoftware/das-frontend#14]
An Organizer creates an event through the use of this form that includes:

- Competition Name
- Federation
- Division
- Age Group
- Proficiency
- Style
- Dances

In viewing the entries at a later time, the following labeling is standardized (like entries.o2cm.com):
{ Division } { Age } { Proficiency } { Style } ({ Dances })

Other JSON parameter:

- Header: `Content-Type: application/json`

Signals (for testing):

200, 400, 401, 403, 500

Reference: [Event API](https://documenter.getpostman.com/view/2986351/RWEfMemn#498102a5-48bd-8b62-957e-f3b0027c3f99)

**Comment by yubing24** [comment]
Implemented
