### ISSUE TITLE
Authentication Credential Service

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das-frontend#41]
Create a service that can parse the JWT authentication token, store token claims, and provide the token to outbound requests.

A reference implementation using Angular can be found here: https://github.com/DancesportSoftware/dasweb/blob/master/src/app/model/account/authentication.service.ts

The Angular component is responsible for:
- [x] Sending user credential to the authentication endpoint: `POST /api/v1.0/account/authenticate`
- [x] Receiving the authentication token (if succeeded) and handle the error (if failed)
- [x] Storing token in the local storage of web browser
- [x] Providing the token to other services that require the authentication token
- [ ] Erasing the token from local storage when user log out

**Comment by shadowlion** [comment]
@yubing24 Close this? Not necessary anymore if we just simply use Firebase credentials to sign in/out

**Comment by yubing24** [comment]
Close issue as authentication is completely migrated to firebase.
