### ISSUE TITLE
Sign in Store

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das-frontend#42]
Create a store (service in Angular) that:
- [x] Send user's login credentials (email and password) to the authentication endpoint `POST /api/v1.0/account/authenticate` and handles responses from the server
- [x] Allow other components to check if the current user is authenticated or logged in
- [x] Log out the current user and clear local storage (if logged in)
- [x] Store user's authentication token and its claims
- [x] Allow other stores and components to get the authentication token and claims (if any)

Reference implementation (Angular): https://github.com/DancesportSoftware/dasweb/blob/development/src/app/shared/service/authentication/authentication.service.ts

**Comment by shadowlion** [comment]
Solved with #90.
