### ISSUE TITLE
Organizer: Create Event View

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das-frontend#86]
Create a view where the organizer can create events for a competition. This view consists of a group of chained select fields.
- [x] Select Competition (competition status must be `Pre-Registration`, or status ID is 1)
  - [x] If the selected value is changed, all the other select field options and bound data **must** reset.
- [x] Select Federation.
  - [x] Pick list should come from `GET /api/v1.0/reference/federation`, or Select Federation Component
  - [x] If selected Federation changes, options in Division, Age, Proficiency, Style, and Dance must reset. Variables that are bound to these fields must reset values as well.
- [x] Select Division.
  - [x] Pick list should come from `GET /api/v1.0/reference/division?federation=<federation id>`
  - [x] If selected Division changes, options in Age, Proficiency, Style, Dances must reset. Variables that are bound to these fields must reset values as well.
- [x] Select Age.
  - [x] Pick list should come from `GET /api/v1.0/reference/age?division=<division id>`, or by creating and using a Select Age component.
  - [x] If selected Age changes, other fields and selected values do not have to be reset.
- [x] Select Proficiency
  - [x] Pick list should come from `GET /api/v1.0/reference/proficiency?division=<division id>`, or by creating and using a Select Proficiency component.
  - [x] If selected Proficiency changes, other fields and selected values do not have to be reset.
- [x] Select Style
  - [x] Pick list should come from `GET /api/v1.0/reference/style`, or by creating an using a Select Style Component
  - [x] If selected Style changes, options for Dance(s) must change as well. Any selected dance(s) should reset as well.
- [x] Multi-select/check Dance(s)
  - [x] Multi-select or check list. Values should come from `GET /api/v1.0/reference/dance?style=<style id>`, or by creating and using a Select Dance component.

Send the payload to `POST /api/v1.0/organizer/event`. Payload details can be found in this Postman doc: https://documenter.getpostman.com/view/2986351/RWaNQ73Z#21163e99-6796-46e1-8a67-6a18a61b4f1c

**Comment by shadowlion** [comment]
Due to #88 solving this issue, I will close this one as well.
