### ISSUE TITLE
Account role cannot be loaded correctly in newly created account

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das-frontend#93]
When a user register a new account, account role is not loaded correctly in the application switch menu after the auto-login.
This is most likely due to the request for account role `/api/v1.0/account/role` was sent to DAS before the role was actually created in DAS, which is `/api/v1.0/account/register`. 
One solution to this problem would be ensuring the request of account role is sent after the server responded to the request of registration.

**Comment by shortaflip** [comment]
So in the switch application menu for a newly registered account it should say the following?
Athlete
Account

and what is being shown is just Athlete?

Is this the bug?  Sorry, not too clear.

**Comment by shadowlion** [comment]
@yubing24 Has this been solved?

**Comment by yubing24** [comment]
Okay. I just tested it and this issue doesn't appear to happen for now.
